version: "3"
services:
  site:
    command: jekyll serve --watch --incremental --livereload
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4001:4000
      - 35730:35729
      - 3001:3000
      #-   80:4000

